### ISSUE TITLE
BUG | 旧API被攻击导致无法下载

### ISSUE THREAD

**Issue by JohnZhou2007** [MCSLTeam/MCSL2#101]
### MCSL2 系统报告

Traceback (most recent call last):
  File "D:\MCSL2-2.2.0.1-Windows-x64\qfluentwidgets\components\widgets\info_bar.py", line 190, in __fadeOut
RuntimeError: wrapped C/C++ object of type QPropertyAnimation has been deleted

### 你在哪方面遇到了问题？

MCSL2下载

### 说明

下载界面如附件

### 附件(可选)

![屏幕截图 2023-08-17 205627](https://github.com/MCSLTeam/MCSL2/assets/138346711/25e7585b-52f0-46c6-8962-a5be9d4b9893)

### 确认

- [X] 我确保我的Issue没有和别人的重复

**Comment by JohnZhou2007** [comment]
: (

**Comment by LxHTT** [comment]
旧API被大手笔DDoS了。静待新版。

**Comment by JohnZhou2007** [comment]
点击导入服务器没反应也是一个道理？

**Comment by HMwancheng** [comment]
准备进来报这个issue的，已经有了就跑/dog

另外，作者有没有加上添加mod功能的想法呢（刚下，有的情况不太了解
）

**Comment by StarryCamile** [comment]
> 准备进来报这个issue的，已经有了就跑/dog
> 
> 另外，作者有没有加上添加mod功能的想法呢（刚下，有的情况不太了解 ）

你是说MCSL2的插件功能吗

**Comment by SadEPa0628** [comment]
> 准备进来报这个issue的，已经有了就跑/dog
> 
> 另外，作者有没有加上添加mod功能的想法呢（刚下，有的情况不太了解 ）

我也是...

**Comment by z0z0r4** [comment]
早就建议过走官方源起码当备线了...

**Comment by z0z0r4** [comment]
> 旧API被大手笔DDoS了。静待新版。

早就建议过走官方源起码当备线了...典

**Comment by LxHTT** [comment]
修复完毕，并且添加了FastMirror下载源。

**Comment by z0z0r4** [comment]
急

**Comment by LxHTT** [comment]
> 急 ![image](https://user-images.githubusercontent.com/78744121/261792662-a4592a84-b21f-4673-b296-c08a4a80dec4.png)

乐子是这样的

**Comment by LxHTT** [comment]
🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣  
🤣🤣👇👇👇👇👇👇👇🤣🤣  
🤣👉🤣👇👇👇👇👇🤣👈🤣  
🤣👉👉🤣👇👇👇🤣👈👈🤣  
🤣👉👉👉🤣👇🤣👈👈👈🤣  
🤣👉👉👉👉🤡👈👈👈👈🤣  
🤣👉👉👉🤣👆🤣👈👈👈🤣  
🤣👉👉🤣👆👆👆🤣👈👈🤣  
🤣👉🤣👆👆👆👆👆🤣👈🤣  
🤣🤣👆👆👆👆👆👆👆🤣🤣  
🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣
