### ISSUE TITLE
BUG | 弹窗报错

### ISSUE THREAD

**Issue by Lingmao9374** [MCSLTeam/MCSL2#108]
### MCSL2 系统报告

MCSL2系统报告：
生成时间：2023-08-21 11:22:14
MCSL2版本：2.2.1.0
操作系统：Windows10 10.0.22621
架构：64bit
内存占用：137.98MB

### 你在哪方面遇到了问题？

MCSL2启动服务器, MCSL2新建服务器, MCSL2下载, MCSL2终端, MCSL2插件, MCSL2设置

### （可能的）诱因：
- 对象已被销毁：在Python中，当一个对象被删除或销毁后，如果尝试对其进行操作，就会出现类似的错误。可能在某个地方删除了 QPropertyAnimation 对象，然后在 __fadeOut 函数中尝试使用它。

- 引用失效：如果对象在作用域内被删除，但仍然持有对它的引用，尝试访问该引用时会导致错误。这通常发生在异步代码中，当一个对象被删除后，它的引用仍然存在于某个回调函数中。

- 线程问题：如果在多线程环境中使用了 QPropertyAnimation 对象，可能会发生线程同步问题，导致对象被删除或访问时的不一致。

### （可能的）解决方法：
- 在关闭弹窗时，您可以主动停止与弹窗相关的动画，以确保动画对象不会在弹窗被销毁后继续操作。您可以使用 stop() 方法来停止动画。

------
触发条件：手动关闭屏幕左下角的绿色弹窗   触发概率99%
进阶：实在闲的没事可以试试，打开插件界面，启用然后立即禁用任意插件。弹窗出现后把鼠标放在"复制到剪切板"会有神奇的事情发生~
![Screenshot 2023-08-21 113108](https://github.com/MCSLTeam/MCSL2/assets/142100614/53e96839-0849-4626-8577-c028d92ba3c6)
![Screenshot 2023-08-21 111938](https://github.com/MCSLTeam/MCSL2/assets/142100614/aa9a2851-5ba9-4b51-b488-8f0a82cc2a36)

### 附件(可选)

![Screenshot 2023-08-21 114038](https://github.com/MCSLTeam/MCSL2/assets/142100614/d5bb7daa-ad94-4a62-a883-009e64d7e092)

### 确认

- [X] 我确保我的Issue没有和别人的重复

**Comment by LxHTT** [comment]
很详细，但是这并非MCSL2的问题。相关问题仍在持续跟进控件库作者中。

**Comment by LxHTT** [comment]
直接屏蔽这个报错了。  
详见提交https://github.com/MCSLTeam/MCSL2/commit/d3de2bda53bd6573f49e91e8062cfaf8c80cc9b6
