### ISSUE TITLE
BUG | 安装插件页出现问题

### ISSUE THREAD

**Issue by FTS427** [MCSLTeam/MCSL2#111]
### MCSL2 系统报告

MCSL2系统报告：
生成时间：2023-08-23 22:05:56
MCSL2版本：2.2.1.0
操作系统：Windows10 10.0.19045
架构：64bit
内存占用：133.37MB

### 你在哪方面遇到了问题？

MCSL2插件

### 说明

当我在点击MCSL2的“安装插件”按钮后，我关掉弹出的“文件资源管理器”，就会出现附件图片里的报错

### 附件(可选)

![image](https://github.com/MCSLTeam/MCSL2/assets/122330825/0f9eedfd-7547-47a4-afd5-86483b97dd56)

### 确认

- [X] 我确保我的Issue没有和别人的重复

**Comment by LxHTT** [comment]
已收到

**Comment by LxHTT** [comment]
https://github.com/MCSLTeam/MCSL2/commit/1df087024e55cdf103514f424b8f8b5a71fe15e2
已修复。
