### ISSUE TITLE
BUG | 下载出现问题

### ISSUE THREAD

**Issue by FTS427** [MCSLTeam/MCSL2#112]
### MCSL2 系统报告

MCSL2系统报告：
生成时间：2023-08-23 22:15:56
MCSL2版本：2.2.1.0
操作系统：Windows10 10.0.19045
架构：64bit
内存占用：133.37MB

### 你在哪方面遇到了问题？

MCSL2下载

### 说明

如附件的图片，我只是想要下载一个purpur核心，为什么会这样？

### 附件(可选)

![image](https://github.com/MCSLTeam/MCSL2/assets/122330825/deb7a98e-1ad2-447a-acfc-9c236050cf60)

### 确认

- [X] 我确保我的Issue没有和别人的重复

**Comment by FTS427** [comment]
不要问我为啥不会把报错信息以完整文本形式呈现，问就是#113导致的问题

**Comment by LxHTT** [comment]
通讯问题

**Comment by LxHTT** [comment]
疑似是aria2c休眠导致的。

**Comment by LxHTT** [comment]
fixed in https://github.com/MCSLTeam/MCSL2/commit/7980bfb09b690970b7955db6134303363315d7bc
