### ISSUE TITLE
BUG | MCSL2控制窗口大小有问题

### ISSUE THREAD

**Issue by FTS427** [MCSLTeam/MCSL2#113]
### MCSL2 系统报告

MCSL2系统报告：
生成时间：2023-08-23 22:05:56
MCSL2版本：2.2.1.0
操作系统：Windows10 10.0.19045
架构：64bit
内存占用：133.37MB

### 你在哪方面遇到了问题？

MCSL2主页

### 说明

如附件的图片，我试图将MCSL2的窗口扩大以至于我可以看到更多的信息，但是好像出问题了

### 附件(可选)

![image](https://github.com/MCSLTeam/MCSL2/assets/122330825/971a35f5-5907-4629-bc51-9df6549a3a26)

### 确认

- [X] 我确保我的Issue没有和别人的重复

**Comment by LxHTT** [comment]
此问题目前不在我们技术层面上，无法解决，需跟进控件库

**Comment by LxHTT** [comment]
然后关于无法完整显示错误的问题，我们会改动为可滚动的

**Comment by LxHTT** [comment]
在提交https://github.com/MCSLTeam/MCSL2/commit/a766f8c06278d214f0ec17a8512e3b38a633ad58中已改为滚动样式
