### ISSUE TITLE
BUG | 点击打开下载文件夹软件崩溃

### ISSUE THREAD

**Issue by 65658dsf** [MCSLTeam/MCSL2#125]
### MCSL2 系统报告

在加载界面点击打开下载文件夹软件崩溃

### 你在哪方面遇到了问题？

MCSL2下载

### 说明

在加载界面点击打开下载文件夹软件崩溃

### 附件(可选)

https://github.com/MCSLTeam/MCSL2/assets/78797486/b1c68f9d-0711-4d64-b664-d18ecb8c04d0

### 确认

- [X] 我确保我的Issue没有和别人的重复

**Comment by LxHTT** [comment]
fixed in https://github.com/MCSLTeam/MCSL2/commit/72c2b955ecfd66eb5862b3bd2dec9cdc36338c62
