### ISSUE TITLE
BUG | “下载Java”功能无法正常使用

### ISSUE THREAD

**Issue by Anshow1** [MCSLTeam/MCSL2#127]
### MCSL2 系统报告

MCSL2系统报告：
生成时间：2023-10-12 22:10:10
Python版本：3.8.10
控件库版本：1.2.2
操作系统：Windows 10 10.0.19045
架构：64bit
内存占用：103.61MB

### 你在哪方面遇到了问题？

MCSL2新建服务器

### 说明

新建服务器中的“下载Java”功能无法正常使用。
具体体现为：进入该模块后，所有下载选项均无法正常加载，均显示黄色警示标记和“加载失败。请尝试刷新，如果仍然失败，请汇报此Bug”文字
网络环境正常，国内网络与国外网络均尝试过

### 附件(可选)

![Bug-Java download 0](https://github.com/MCSLTeam/MCSL2/assets/125620077/503c7979-18be-40f3-b30c-79e7f7d8b57e)
![Bug-Java download 1](https://github.com/MCSLTeam/MCSL2/assets/125620077/deda3cc7-0e99-42bc-a940-47d8d56d49d1)

### 确认

- [X] 我确保我的Issue没有和别人的重复

**Comment by ltzXiaoYanMo** [comment]
你发两个了（

**Comment by LxHTT** [comment]
检查MCSL2/MCSL2_Config.json文件的`nodeMCSLAPI`键值

**Comment by LxHTT** [comment]
查看https://hardbin.com能否访问

**Comment by Anshow1** [comment]
> 检查MCSL2/MCSL2_Config.json文件的`nodeMCSLAPI`键值

![nodeMCSLAPI](https://github.com/MCSLTeam/MCSL2/assets/125620077/630e1001-e1b2-4f19-8b59-81aee43411e0)

**Comment by Anshow1** [comment]
> 查看[https://hardbin.com能否访问](https://hardbin.com%E8%83%BD%E5%90%A6%E8%AE%BF%E9%97%AE)



> 查看[https://hardbin.com能否访问](https://hardbin.com%E8%83%BD%E5%90%A6%E8%AE%BF%E9%97%AE)

网站会被卡巴斯基拦截，关闭卡巴斯基后可正常访问，但是java下载还是加载失败
![hardbin](https://github.com/MCSLTeam/MCSL2/assets/125620077/59d0583c-a02c-4f9f-b4b6-ab2af4802e46)

**Comment by LxHTT** [comment]
那就是杀毒软件问题。
