### ISSUE TITLE
BUG | “从下载的核心中导入”功能出错

### ISSUE THREAD

**Issue by Anshow1** [MCSLTeam/MCSL2#129]
### MCSL2 系统报告

MCSL2系统报告：
生成时间：2023-10-12 22:31:11
Python版本：3.8.10
控件库版本：1.2.2
操作系统：Windows 10 10.0.19045
架构：64bit
内存占用：89.0MB

### 你在哪方面遇到了问题？

MCSL2新建服务器

### 说明

在新建服务器时选择“从下载的核心中导入”功能后显示出错
具体体现为：核心列表中的核心详情全部透明，能看到3个核心的列表轮廓，但是轮廓内一片透明

### 附件(可选)

![Bug-核心导入 0](https://github.com/MCSLTeam/MCSL2/assets/125620077/cfa3a73e-af66-474a-b48a-eb68aa8f4bb9)
![Bug-核心导入 1](https://github.com/MCSLTeam/MCSL2/assets/125620077/edbfe0d0-c61a-4435-b781-ea10eb5888d5)
![Bug-核心导入 2](https://github.com/MCSLTeam/MCSL2/assets/125620077/2919c08a-d171-4c52-92fe-b41678dabbe2)

### 确认

- [X] 我确保我的Issue没有和别人的重复

**Comment by LxHTT** [comment]
请发送MCSL2/Downloads/download_entries.json文件内容，我无法复现。  
![image](https://github.com/MCSLTeam/MCSL2/assets/98154001/47d67da1-0157-4743-9115-dcaaf0fc91b8)
![image](https://github.com/MCSLTeam/MCSL2/assets/98154001/88afd1e2-8168-4c0f-a81f-9a3425c88797)

**Comment by Anshow1** [comment]
> 请发送MCSL2/Downloads/download_entries.json文件内容，我无法复现。 ![image](https://user-images.githubusercontent.com/98154001/274661784-47d67da1-0157-4743-9115-dcaaf0fc91b8.png) ![image](https://user-images.githubusercontent.com/98154001/274661909-88afd1e2-8168-4c0f-a81f-9a3425c88797.png)

![download_entire](https://github.com/MCSLTeam/MCSL2/assets/125620077/f3974c8a-5819-43be-9db5-eb11bcec2916)
