### ISSUE TITLE
出现开始画面后闪退

### ISSUE THREAD

**Issue by Bloodsans** [MCSLTeam/MCSL2#131]
### MCSL2 系统报告

[MCSL2_2023-11-03_22.log](https://github.com/MCSLTeam/MCSL2/files/13251869/MCSL2_2023-11-03_22.log)

### 你在哪方面遇到了问题？

启动/关闭MCSL2

### 说明

启动时出现图片所示页面后闪退，任务栏有图标，点击显示隐藏的图标就会消失

### 附件(可选)

![ef79b6f72b73bc15255b0be515660581](https://github.com/MCSLTeam/MCSL2/assets/149809053/05c3499c-2308-45ec-8639-7d61e4e18fc2)
![4cfa4b3e191382b6464888acd491ec9a_0](https://github.com/MCSLTeam/MCSL2/assets/149809053/6ca25f0a-78f8-4cdf-9b2f-0ff7cc4d4489)

### 确认

- [X] 我确保我的Issue没有和别人的重复

**Comment by LxHTT** [comment]
检查任务管理器，杀掉所有MCSL2看看

**Comment by ltzXiaoYanMo** [comment]
在log文件中未查看到ERROR和Warning等字样，可能只是主界面看不到

**Comment by Bloodsans** [comment]
> 检查任务管理器，杀掉所有MCSL2看看

闪退后就没看到MCSL2的进程了

**Comment by ltzXiaoYanMo** [comment]
> > 检查任务管理器，杀掉所有MCSL2看看
> 
> 闪退后就没看到MCSL2的进程了

~~抱歉忘记看了~~<br>
目前来看的话 可能是系统版本的问题 具体可以试试使用后期版本来尝试<br>
~~或者，换台电脑？（~~

**Comment by ltzXiaoYanMo** [comment]
因超过很久时间不回复 我决定关闭Issue 若后期版本还有问题重新发下Issue
