### ISSUE TITLE
BUG | 感觉动画有一点卡卡的，像30帧的样子

### ISSUE THREAD

**Issue by youlan2333** [MCSLTeam/MCSL2#135]
### MCSL2 系统报告

MCSL2系统报告：
生成时间：2023-12-22 16:32:29
Python版本：3.8.10
控件库版本：1.4.0
操作系统：Windows 10 10.0.19045
架构：64bit
内存占用：214.39MB

### 你在哪方面遇到了问题？

MCSL2主页, MCSL2启动服务器, MCSL2新建服务器, MCSL2下载, MCSL2终端, MCSL2插件, MCSL2设置, 启动/关闭MCSL2, MCSL2更新

### 说明

如题

### 确认

- [X] 我确保我的Issue没有和别人的重复

**Comment by ltzXiaoYanMo** [comment]
能发送下配置信息吗？

**Comment by youlan2333** [comment]
> 能发送下配置信息吗？

![image](https://github.com/MCSLTeam/MCSL2/assets/64688148/ad6eea0a-0c7a-4cbd-b29f-4ad595be9dee)
![image](https://github.com/MCSLTeam/MCSL2/assets/64688148/32927910-eaf4-4c2d-83dd-a69a3713147d)

**Comment by ltzXiaoYanMo** [comment]
收到，这个得和上级说下了，不排除是我们选的PyQt效果本身问题。@LxHTT

**Comment by youlan2333** [comment]
> 收到，这个得和上级说下了，不排除是我们选的PyQt效果本身问题。@LxHTT

好的😢

**Comment by ltzXiaoYanMo** [comment]
![图片](https://github.com/MCSLTeam/MCSL2/assets/115706851/f631405d-92a9-4242-910e-ba21d2cb351f)

**Comment by youlan2333** [comment]
> ![图片](https://private-user-images.githubusercontent.com/115706851/292450964-f631405d-92a9-4242-910e-ba21d2cb351f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzY5OTIsIm5iZiI6MTcwMzIzNjY5MiwicGF0aCI6Ii8xMTU3MDY4NTEvMjkyNDUwOTY0LWY2MzE0MDVkLTkyYTktNDI0Mi05MTBlLWJhMjFkMmNiMzUxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMlQwOTE4MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMWY0ZjA3ZjEzMzY4MWFiMjg3NzQ0ZmYyNjY4MmRiODQ5OGUyYzE3ODY1YzExZGM4OTI0NjAwYjIzNzUxY2Q3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6C1Kf5CdE5J6hNwOMUgrSlmTi2-slkF-wIZCacpXSJs)

emmm，一直插着电源而且还是笔记本性能模式加win卓越性能💧

**Comment by ltzXiaoYanMo** [comment]
那我实在没办法了，等落雪来处理吧（

**Comment by LxHTT** [comment]
疑似Qt5毛病 稍安勿躁

**Comment by David-xian66** [comment]
疑似python运行过快，建议跳槽cpp（doge

**Comment by LxHTT** [comment]
下个版本测试一下，如果还不行那就真的没能力了: (
