### ISSUE TITLE
BUG | Paper服务器在反复进入“管理”时会多次拷贝自身

### ISSUE THREAD

**Issue by kong-que-dnf123** [MCSLTeam/MCSL2#142]
### MCSL2 系统报告

MCSL2系统报告：
生成时间：2024-01-17 09:43:54
Python版本：3.8.10
控件库版本：1.4.0
操作系统：Windows 11 10.0.22631
架构：64bit
内存占用：164.48MB

### 你在哪方面遇到了问题？

MCSL2主页, MCSL2更改/删除服务器

### 说明

如题，在进入“管理”后点击左边进入其他界面再切回来就会在“管理”界面额外出现一个相同的服务器
~我有两个服务器但只有上面那个出现了拷贝自身的问题~
edit：
重开MCSL会清除拷贝出来的服务器，但相同操作仍会继续拷贝
### 附件(可选)

https://github.com/MCSLTeam/MCSL2/assets/120994373/a7aabedd-8e5b-4d7e-ab92-fb75fd966e12

### 确认

- [X] 我确保我的Issue没有和别人的重复

**Comment by LxHTT** [comment]
Fixed in dev version
