### ISSUE TITLE
BUG | 测试版出现错误

### ISSUE THREAD

**Issue by Leonmmcoset** [MCSLTeam/MCSL2#145]
### MCSL2 系统报告

生成时间：2024-01-21 14:32:32
MCSL2版本：2.2.3.3
Python版本：3.8.10
控件库版本：1.4.5
操作系统：Windows 11 10.0.22621
CPU：AMD64 Family 25 Model 116 Stepping 1, AuthenticAMD
架构：64bit
内存占用：226.54MB

### 你在哪方面遇到了问题？

MCSL2终端

### 说明

我在测试版2.2.3.3出现终端弹窗
错误：TypeError: invalid argument to sipBadCatcherResult()

### 确认

- [X] 我确保我的Issue没有和别人的重复

**Comment by LxHTT** [comment]
Ignored this exception in [86cab1f: Fuck you sipBadCatcherResult](https://github.com/MCSLTeam/MCSL2/commit/86cab1fe4359aef242b3a53ca0696ceade3f4dcf)
