### ISSUE TITLE
BUG | 在线玩家列表Bug

### ISSUE THREAD

**Issue by Leonmmcoset** [MCSLTeam/MCSL2#146]
### MCSL2 系统报告

生成时间：2024-01-21 19:32:12
MCSL2版本：2.2.3.4
Python版本：3.8.10
Qt版本：5.15.2
QFluentWidgets版本：1.4.6
操作系统：Windows 11 10.0.22621
CPU：AMD64 Family 25 Model 116 Stepping 1, AuthenticAMD
架构：64bit
内存占用：237.13MB

### 你在哪方面遇到了问题？

MCSL2终端

### 说明

在线玩家列表显示有误

### 附件(可选)

https://github.com/MCSLTeam/MCSL2/assets/152147508/99d3182d-4c34-49bf-865e-1a539827cc46

### 确认

- [X] 我确保我的Issue没有和别人的重复

**Comment by ltzXiaoYanMo** [comment]
别一个"见附件"就结束了，可能开发组里有些人没太看懂视频里的问题所在（

**Comment by LxHTT** [comment]
Fixed in https://github.com/MCSLTeam/MCSL2/commit/0679af336e0de816b6bf18e1ff90a693b8fe9587
