### ISSUE TITLE
BUG | 终端重复

### ISSUE THREAD

**Issue by Leonmmcoset** [MCSLTeam/MCSL2#148]
### MCSL2 系统报告

生成时间：2024-01-22 22:00:15
MCSL2版本：2.2.3.4
Python版本：3.8.10
Qt版本：5.15.2
QFluentWidgets版本：1.4.6
操作系统：Windows 11 10.0.22621
CPU：AMD64 Family 25 Model 116 Stepping 1, AuthenticAMD
架构：64bit
内存占用：178.09MB

### 你在哪方面遇到了问题？

MCSL2终端

### 说明

当重启终端时会出现重复

### 附件(可选)

https://github.com/MCSLTeam/MCSL2/assets/152147508/3371d95a-14a6-4ecb-bed6-ac4515b123ab

### 确认

- [X] 我确保我的Issue没有和别人的重复

**Comment by LxHTT** [comment]
Fixed in https://github.com/MCSLTeam/MCSL2/commit/becc63cd110539e871acef79fcec2b414b711c47
