### ISSUE TITLE
BUG | 2.2.3.5出现在线人数列表问题

### ISSUE THREAD

**Issue by Leonmmcoset** [MCSLTeam/MCSL2#149]
### MCSL2 系统报告

生成时间：2024-01-23 10:41:24
MCSL2版本：2.2.3.5 Beta Channel 24122
Python版本：3.8.10
Qt版本：5.15.2
QFluentWidgets版本：1.4.6
操作系统：Windows 11 10.0.22621
CPU：AMD64 Family 25 Model 116 Stepping 1, AuthenticAMD
架构：64bit
内存占用：177.42MB

### 你在哪方面遇到了问题？

MCSL2终端

### 说明

还是会出现，没修复啊

### 附件(可选)

![屏幕截图 2024-01-23 104204](https://github.com/MCSLTeam/MCSL2/assets/152147508/553cd38a-9214-4367-b9d9-8b6b416bd919)

### 确认

- [x] 我确保我的Issue没有和别人的重复

**Comment by ltzXiaoYanMo** [comment]
目前在测试环境中没发现此问题，只能找人试试看qwq

**Comment by LxHTT** [comment]
已修复
