### ISSUE TITLE
BUG | 编辑配置文件无法保存

### ISSUE THREAD

**Issue by Leonmmcoset** [MCSLTeam/MCSL2#151]
### MCSL2 系统报告

生成时间：2024-01-24 13:03:32
MCSL2版本：2.2.3.5 Beta Channel 24122
Python版本：3.8.10
Qt版本：5.15.2
QFluentWidgets版本：1.4.6
操作系统：Windows 11 10.0.22621
CPU：AMD64 Family 25 Model 116 Stepping 1, AuthenticAMD
架构：64bit
内存占用：200.29MB

### 你在哪方面遇到了问题？

MCSL2终端

### 说明

配置文件修改后无法保存

### 附件(可选)

https://github.com/MCSLTeam/MCSL2/assets/152147508/366704cf-20c1-42b5-9d95-1f95c31c272f

### 确认

- [X] 我确保我的Issue没有和别人的重复

**Comment by ltzXiaoYanMo** [comment]
你可以尝试关闭这个`start.sh`触发自动保存试试看<br>
MCSL2的测试版本当中你只能使用关闭`文件窗口`才可保存

**Comment by Leonmmcoset** [comment]
关闭就可以了（为什么不增加保存按钮或ctrl+s呢？）

**Comment by ltzXiaoYanMo** [comment]
好问题

@LxHTT

**Comment by LeonMMcoset2** [comment]
为啥又重开了？

**Comment by LxHTT** [comment]
有概率会在关闭时报错

**Comment by ltzXiaoYanMo** [comment]
> 可以做个类似idea那种实时保存

也不是不行其实....但我认为尽量还是把选择权交给用户吧

**Comment by LxHTT** [comment]
> 可以做个类似idea那种实时保存

想法是很好，但是重点在于现在在关闭配置文件标签页时有概率报错

**Comment by kitUIN** [comment]
还有一个bug
点击左侧,切换标签了但是内容没切换

**Comment by kitUIN** [comment]
> > 可以做个类似idea那种实时保存
> 
> 想法是很好，但是重点在于现在在关闭配置文件标签页时有概率报错

现在可以稳定复现
操作如下:
1. 左侧点击几个文件
2. 点×几个留下一个
3. 重新在左侧点击你×的那些文件
4. 尝试把重新点击的×掉,就会报错

**Comment by AresConnor** [comment]
#159
