### ISSUE TITLE
官网无法访问

### ISSUE THREAD

**Issue by RhoPaper** [MCSLTeam/MCSL2#152]
### MCSL2 系统报告

mcsl.com.cn站点访问时出错

### 你在哪方面遇到了问题？

MCSL2主页

### 说明

CDN坏了

### 附件(可选)

![RTX截图未命名](https://github.com/MCSLTeam/MCSL2/assets/128818826/b310b806-6c95-4626-94e9-e182e5e2823d)

### 确认

- [X] 我确保我的Issue没有和别人的重复

**Comment by Leonmmcoset** [comment]
重新打开试试，我的没坏

**Comment by ltzXiaoYanMo** [comment]
目前官网并没有出现`网站请求出错`，请尝试强制刷新浏览器缓存
