### ISSUE TITLE
BUG | 消息重复

### ISSUE THREAD

**Issue by Leonmmcoset** [MCSLTeam/MCSL2#153]
### MCSL2 系统报告

生成时间：2024-01-26 10:33:24
MCSL2版本：2.2.3.5 Beta Channel 24122
Python版本：3.8.10
Qt版本：5.15.2
QFluentWidgets版本：1.4.6
操作系统：Windows 10 10.0.20348
CPU：Intel64 Family 6 Model 156 Stepping 0, GenuineIntel
架构：64bit
内存占用：212.67MB

### 你在哪方面遇到了问题？

MCSL2终端

### 说明

没有修复关闭服务器消息重复问题

### 附件(可选)

![image](https://github.com/MCSLTeam/MCSL2/assets/152147508/60b72be4-c21f-4650-83d2-f73c867f26ae)

### 确认

- [X] 我确保我的Issue没有和别人的重复

**Comment by ltzXiaoYanMo** [comment]
请问这个bug如何复现呢

**Comment by LeonMMcoset2** [comment]
我是LeonMMcoset（报告bug的用户）的小号
跟以前一样，在终端窗口关闭再启动服务器再关闭就可以出现了。
：-）

**Comment by AresConnor** [comment]
becc63cd110539e871acef79fcec2b414b711c47 fixed

**Comment by AresConnor** [comment]
等新版本发了就可以close了

**Comment by ltzXiaoYanMo** [comment]
其实你现在就可以close completed了（

**Comment by LxHTT** [comment]
由于MCServerLauncher Future的开发工作繁忙，本项目即将停止维护，很抱歉无法为此问题提供技术支持。
