### ISSUE TITLE
BUG | BungeeCord服务端无法正常输入命令

### ISSUE THREAD

**Issue by StarryCamile** [MCSLTeam/MCSL2#160]
### MCSL2 系统报告

生成时间：2024-02-23 17:33:05  
MCSL2版本：2.2.4.2 Stable Channel 24208  
Python版本：3.11.4  
Qt版本：5.15.2  
QFluentWidgets版本：1.5.1  
操作系统：Windows 10 10.0.19044  
CPU：Intel64 Family 6 Model 166 Stepping 0, GenuineIntel  
架构：64bit   
内存占用：243.49MB  

### 你在哪方面遇到了问题？

MCSL2终端

### 说明

在使用BungeeCord服务端时，启动后无法正常输入命令，按回车或按钮无反应。
![图片](https://github.com/MCSLTeam/MCSL2/assets/123795586/b570525b-dec7-4066-a00d-ad54005f09c3)
在输出端口时，似乎少了一位？

### 如何复现这个bug？

如说明

### 确认

- [x] 我确保我的Issue没有和别人的重复

**Comment by LxHTT** [comment]
本来大多数服务器会因为多出一个换行符导致终端看着很奇怪才烂掉最后一位，不知道为什么这个不会多输出东西。
我建议直接做服务器类型判断`BungeeCord`就少吞一位

**Comment by ltzXiaoYanMo** [comment]
在 `MCServerLauncher` Developer 版本 2.2.4.2 中暂未发现此问题，目前需要更多人手测试
