### ISSUE TITLE
BUG | (在这里给Issue命名)X86 is x64.

### ISSUE THREAD

**Issue by hsjdhudn** [MCSLTeam/MCSL2#164]
### MCSL2 系统报告

Can't open

### 你在哪方面遇到了问题？

MCSL2主页

### 说明

My computer is X86, so I downloaded the old version of x86 compressed package, and it doesn't work as a result. When I checked with a virtual machine, it was actually x64 compressed package. Aren't you a liar?

### 如何复现这个bug？

Pop-up application is not suitable for your computer v
![Uploading 4a444f313c6a36b6336f08363ca05728.png…]()
ersion.

### 附件(可选)

![4a444f313c6a36b6336f08363ca05728](https://github.com/MCSLTeam/MCSL2/assets/159747651/bc0aeb05-43a8-4c33-aaef-c9a5aa9e1ef3)

### 确认

- [X] 我确保我的Issue没有和别人的重复

**Comment by kitUIN** [comment]
no longer support x86

**Comment by LxHTT** [comment]
很早就不支持32位了，自己翻release
