### ISSUE TITLE
BUG | 卡爆

### ISSUE THREAD

**Issue by bmlingqi** [MCSLTeam/MCSL2#177]
### MCSL2 系统报告

null

### 你在哪方面遇到了问题？

MCSL2主页

### 说明

启动后长时间不操作启动器界面然后去操作操作直接卡爆。或许是兼容性极差

### 如何复现这个bug？

启动软件然后不管，丢个几个小时。然后再去操作软件的界面元素

### 确认

- [X] 我确保我的Issue没有和别人的重复

**Comment by XieXiLin2** [comment]
细说，可以的话传份日志

**Comment by Tigercrl** [comment]
在没有错误日志的情况下，诊断任何问题无异于闭眼驾车
 - Apache官方文档Getting Started 篇章

我只能给你算一卦（

**Comment by ltzXiaoYanMo** [comment]
![878273e6047685ee398f166c4a89cead](https://github.com/MCSLTeam/MCSL2/assets/115706851/15b84d17-e5d6-4d81-90cc-a7be18e7026a)

**Comment by Tigercrl** [comment]
先自行排除是否为操作系统的问题

**Comment by XieXiLin2** [comment]
应为系统调度问题，还请您自行排查一下。
