### ISSUE TITLE
BUG | 生成启动脚本时缺少 "\"

### ISSUE THREAD

**Issue by ccyy512** [MCSLTeam/MCSL2#178]
### MCSL2 系统报告

没有

### 你在哪方面遇到了问题？

MCSL2更改/删除服务器

### 说明

如标题，并且我试了无论哪个版本都有这个问题

### 如何复现这个bug？

生成启动脚本

### 附件(可选)

![a6729cbd369be37113584a0a3fb76ea6](https://github.com/MCSLTeam/MCSL2/assets/148406068/162d792a-2da0-472d-bc27-8cf88b26ccda)
如图所示，我的服务器名称叫194

### 确认

- [X] 我确认已经熟读了[提问的智慧](https://lug.ustc.edu.cn/wiki/doc/smart-questions/)
- [X] 我确保我的Issue没有和别人的重复

**Comment by Tigercrl** [comment]
已确认，在修

**Comment by LxHTT** [comment]
we are considering convert it into a PowerShell script. Fixing.

**Comment by Tigercrl** [comment]
#179
