### ISSUE TITLE
更新2.2.6.0之后无法打开了

### ISSUE THREAD

**Issue by HMwancheng** [MCSLTeam/MCSL2#183]
### MCSL2 系统报告

打不开

### 你在哪方面遇到了问题？

启动/关闭MCSL2

### 说明

软件打不开

### 如何复现这个bug？

打不开

### 确认

- [X] 我确认已经熟读了[提问的智慧](https://lug.ustc.edu.cn/wiki/doc/smart-questions/)
- [X] 我确保我的Issue没有和别人的重复

**Comment by Tigercrl** [comment]
在没有错误日志的情况下，诊断任何问题无异于闭眼驾车

**Comment by HMwancheng** [comment]
打不开啊喂 
不是不想不想丢日志

**Comment by Tigercrl** [comment]
新版本似乎确实有问题，尝试回退到2.2.5.1

**Comment by HMwancheng** [comment]
![Uploading image.png…]()
我直接jar文件启动了，静待修复

**Comment by Tigercrl** [comment]
#184

**Comment by Tigercrl** [comment]
emm这可能不是问题的主要原因

**Comment by YuShanNan** [comment]
我也打不开，完全没反应

**Comment by LxHTT** [comment]
我们还在找问题  耐心等候  现在先用旧版

**Comment by ltzXiaoYanMo** [comment]
<https://github.com/MCSLTeam/MCSL2/actions/runs/9729779676>

我不清楚能不能用...

**Comment by YuShanNan** [comment]
> https://github.com/MCSLTeam/MCSL2/actions/runs/9729779676
> 
> 我不清楚能不能用...

在我的电脑上可以正常启动

**Comment by LxHTT** [comment]
Nuitka导致的
