### ISSUE TITLE
BUG | 导出启动脚本错误

### ISSUE THREAD

**Issue by Leonmmcoset** [MCSLTeam/MCSL2#185]
### MCSL2 系统报告

生成时间: 2024-06-07 18:15:13
MCSL2 版本: 2.2.5.1 Stable Channel 24309
Python 版本: 3.8.10
Qt 版本: 5.15.2
QFluentWidgets 版本: 1.5.4
操作系统: Windows 11 10.0.22631
CPU: AMD64 Family 25 Model 116 Stepping 1, AuthenticAMD
架构: 64bit
内存占用: 126.88 MB

### 你在哪方面遇到了问题？

MCSL2终端

### 说明

导出脚本后报错：
Traceback (most recent call last):
  File "D:\mcsl\MCSL2Lib\ServerControllers\windowCreator.py", line 368, in genRunScript
AttributeError: 'ServerLauncher' object has no attribute 'jvmArg'

### 如何复现这个bug？

https://github.com/MCSLTeam/MCSL2/assets/152147508/ee69ee4f-6012-4733-91c6-04d463b67b7f

### 确认

- [X] 我确认已经熟读了[提问的智慧](https://lug.ustc.edu.cn/wiki/doc/smart-questions/)
- [X] 我确保我的Issue没有和别人的重复

**Comment by LxHTT** [comment]
This is a duplicate issue
