### ISSUE TITLE
BUG | 服务器关闭消息重复

### ISSUE THREAD

**Issue by Leonmmcoset** [MCSLTeam/MCSL2#191]
### MCSL2 系统报告

生成时间: 2024-06-23 10:15:46
MCSL2 版本: 2.2.5.1 Stable Channel 24309
Python 版本: 3.8.10
Qt 版本: 5.15.2
QFluentWidgets 版本: 1.5.4
操作系统: Windows 10 10.0.20348
CPU: Intel64 Family 6 Model 156 Stepping 0, GenuineIntel
架构: 64bit
内存占用: 211.71 MB

### 你在哪方面遇到了问题？

MCSL2终端

### 说明

我曾经发过issues，但是LxHTT说是插件的问题，就没管
但是当我用**原版**服务器时，也出了这个问题
那就不是插件的问题了

### 如何复现这个bug？

重启服务器2次

### 附件(可选)

（服务器无法传输图片，只能拿以前的图片供参考）
![屏幕截图 2024-01-21 163636](https://github.com/MCSLTeam/MCSL2/assets/152147508/269dcad0-eb3b-413a-a9e7-d73e78a1b249)

### 确认

- [x] 我确认已经熟读了[提问的智慧](https://lug.ustc.edu.cn/wiki/doc/smart-questions/)
- [X] 我确保我的Issue没有和别人的重复

**Comment by LxHTT** [comment]
问题重复出现，应该重新请求打开以前的issue而不是直接新开，我会直接删掉
