### ISSUE TITLE
BUG | 打包错误导致无法启动

### ISSUE THREAD

**Issue by SDAFAGGG** [MCSLTeam/MCSL2#194]
### MCSL2 系统报告

Python 版本: 3.8.10
Qt 版本: 5.15.2
QFluentWidgets 版本: 1.5.4
操作系统: Windows 10 10.0.19045
CPU: AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD
架构: 64bit
内存占用: 149.07 MB

### 你在哪方面遇到了问题？

启动/关闭MCSL2

### 说明

2.2.6.1启动器无法启动

### 如何复现这个bug？

2.2.6.1点击启动器后无任何响应，管理员运行同样无响应
2.2.5.1可以正常启动

### 确认

- [X] 我确认已经熟读了[提问的智慧](https://lug.ustc.edu.cn/wiki/doc/smart-questions/)
- [X] 我确保我的Issue没有和别人的重复
- [X] 我确保我的Issue真的没有和别人的重复，并已知晓随意新建相同话题的议题可能导致被封禁
- [X] 我保证我的Issue没有和别人的重复，并且愿意承担随意回答此问题的后果

**Comment by XieXiLin2** [comment]
是否有生成MCSL2相关配置文件（MCSL2目录下）

**Comment by SDAFAGGG** [comment]
未生成
![{WI22S%BRUEZ0M@WC1%E34V](https://github.com/user-attachments/assets/34a65d72-d791-400e-8b52-f826a4981847)

**Comment by LxHTT** [comment]
检查杀毒软件

**Comment by SDAFAGGG** [comment]
> 检查杀毒软件

火绒，无拦截记录
![~SH6%~M7AU2D2IH0EJOHO`0](https://github.com/user-attachments/assets/2bf060c6-268e-410f-8ea9-412dc086c466)

**Comment by xiaoyuzhou1535** [comment]
windows11 23h2一样情况

**Comment by Vanisper** [comment]
测试了一下  `releases` 上的确实无法运行，也无报错提示（建议打包一个有控制台的版本，或许能找到端倪？），
于是我自己编译了一份，但是因为没装VS，所以使用的是 mingw64 进行构建的，`pyproject.toml` 修改如下：

``` toml
# 编译选项
clang = false
# msvc = "latest"
mingw64 = true
```

自己编译的能正常运行，猜测是因为机子的差异性导致的打包结果不一致？

**Comment by shenjackyuanjie** [comment]
> 测试了一下 `releases` 上的确实无法运行，也无报错提示（建议打包一个有控制台的版本，或许能找到端倪？）， 于是我自己编译了一份，但是因为没装VS，所以使用的是 mingw64 进行构建的，`pyproject.toml` 修改如下：
> 
> ```toml
> # 编译选项
> clang = false
> # msvc = "latest"
> mingw64 = true
> ```
> 
> 自己编译的能正常运行，猜测是因为机子的差异性导致的打包结果不一致？

哥们…… 你带了 mingw32 就别加 clang 啊……
能跑也是个奇迹

**Comment by Vanisper** [comment]
> > 测试了一下 `releases` 上的确实无法运行，也无报错提示（建议打包一个有控制台的版本，或许能找到端倪？）， 于是我自己编译了一份，但是因为没装VS，所以使用的是 mingw64 进行构建的，`pyproject.toml` 修改如下：
> > ```toml
> > # 编译选项
> > clang = false
> > # msvc = "latest"
> > mingw64 = true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 自己编译的能正常运行，猜测是因为机子的差异性导致的打包结果不一致？
> 
> 哥们…… 你带了 mingw32 就别加 clang 啊…… 能跑也是个奇迹

哦？我已经`false`了

**Comment by Vanisper** [comment]
> （草，我瞎，当我没说（ 我去看看build咋了

项目很不错，无意中路过👍

**Comment by shenjackyuanjie** [comment]
（构建的选项的生成库是我写的（

**Comment by LxHTT** [comment]
Nuitka最近挺奇怪的。有部分用户正常，也有很多出错的。

**Comment by AhDuiDuiDui** [comment]
+1，2.2.6.0可以正常打开

**Comment by ltzXiaoYanMo** [comment]
此 Issues 在群内已经提出过相同问题，这里不再赘述。

暂时先使用 MCSL 2.2.6.0 吧（

**Comment by shenjackyuanjie** [comment]
去试试 2.2.6.3 去，各位

**Comment by LxHTT** [comment]
v2.2.6.3已修复。
