### ISSUE TITLE
BUG | MCSL2 主页公告

### ISSUE THREAD

**Issue by Muhu-C** [MCSLTeam/MCSL2#196]
### MCSL2 系统报告

生成时间: 2024-08-09 16:04:31
MCSL2 版本: 2.2.6.3 Stable Channel 24809
Python 版本: 3.8.10
Qt 版本: 5.15.2
QFluentWidgets 版本: 1.6.0
操作系统: Windows 11 10.0.22631
CPU: Intel64 Family 6 Model 151 Stepping 5, GenuineIntel
架构: 64bit
内存占用: 152.05 MB

### 你在哪方面遇到了问题？

MCSL2主页

### 说明

![image](https://github.com/user-attachments/assets/bc527bd4-d25e-49b1-9ea4-a6c40b8b969d)
是刚更新还是忘了，截至2024/8/9 16:08还没更新公告
如果公告是在api获取的话就当我问题没说
我也不知道群里是怎样的，不好意思

### 如何复现这个bug？

打开程序就能复现，和系统无关

### 确认

- [X] 我确认已经熟读了[提问的智慧](https://lug.ustc.edu.cn/wiki/doc/smart-questions/)
- [X] 我确保我的Issue没有和别人的重复
- [X] 我确保我的Issue真的没有和别人的重复，并已知晓随意新建相同话题的议题可能导致被封禁
- [X] 我保证我的Issue没有和别人的重复，并且愿意承担随意回答此问题的后果

**Comment by Tigercrl** [comment]
2.2.6.3稳定性未知，能跑再改

**Comment by Muhu-C** [comment]
除了Aria2没法启动之外好像没啥问题

**Comment by Tigercrl** [comment]
你能跑不代表都能跑，如2.2.6.1有些用户能开有些开了没反应

**Comment by shenjackyuanjie** [comment]
草（
我的问题（
应用内没改，不过反正都是测试版（

**Comment by Muhu-C** [comment]
好吧

**Comment by Tigercrl** [comment]
带aria2的2.2.6.3我等会上传

**Comment by LxHTT** [comment]
已修改。
