### ISSUE TITLE
BUG | 窗口模式下程序尺寸异常

### ISSUE THREAD

**Issue by qsmmzhn** [MCSLTeam/MCSL2#197]
### MCSL2 系统报告

生成时间: 2024-08-17 10:38:28
MCSL2 版本: 2.2.6.3 Stable Channel 24809
Python 版本: 3.8.10
Qt 版本: 5.15.2
QFluentWidgets 版本: 1.6.0
操作系统: Windows 11 10.0.22631
CPU: Intel64 Family 6 Model 170 Stepping 4, GenuineIntel
架构: 64bit
内存占用: 176.58 MB

### 你在哪方面遇到了问题？

MCSL2主页

### 说明

![屏幕截图 2024-08-17 103934](https://github.com/user-attachments/assets/3be8d1a3-ff9a-4b96-ada7-df2e4572a984)
![屏幕截图 2024-08-17 104207](https://github.com/user-attachments/assets/c53b1c3d-debe-46de-be57-db953af3e27c)
![image](https://github.com/user-attachments/assets/fda465df-389c-4154-a562-400fe64ad80d)
![image](https://github.com/user-attachments/assets/ce7484c6-0e0a-4b18-a408-8e383c8685ba)
图一是直接打开显示的窗口，看不到右侧边界，且无法缩小
图二是向左拖动十几次后显示的窗口，还是看不到右侧边界，且无法再拖动
图三是最大化后正常的界面，可以看到右侧边界
图四是多任务预览里显示的程序预览

有没有可能是公告的问题？

### 如何复现这个bug？

非常简单，关掉重开即可

### 确认

- [X] 我确认已经熟读了[提问的智慧](https://lug.ustc.edu.cn/wiki/doc/smart-questions/)
- [X] 我确保我的Issue没有和别人的重复
- [X] 我确保我的Issue真的没有和别人的重复，并已知晓随意新建相同话题的议题可能导致被封禁
- [X] 我保证我的Issue没有和别人的重复，并且愿意承担随意回答此问题的后果

**Comment by LxHTT** [comment]
系API侧问题 正在排查。

**Comment by LxHTT** [comment]
请重启MCSL2，并再次查看是否仍存在此问题

**Comment by qsmmzhn** [comment]
没问题了，显示正常
