### ISSUE TITLE
BUG｜Nuitka在macOS平台打包不正常

### ISSUE THREAD

**Issue by LxHTT** [MCSLTeam/MCSL2#32]
- [x] 并非电脑自身造成
- [x] MCSL 2 运行在受官方支持的平台上
___

### 一般要素
- 系统：macOS 11
- 架构：x64
- MCSL 2 版本：https://github.com/LxHTT/MCSL2/releases/tag/2023-03-28-12-17

### 问题描述
macOS没一个能用的版本

### 复现
每个都不行。

### 可能的解决方案（？）
不知道，需要测试，大众协助解决

**Comment by FTS427** [comment]
有没有一种可能MacOS上是不支持Qt的，需要用到Object-C？（我啥也不知道

**Comment by LxHTT** [comment]
> 有没有一种可能MacOS上是不支持Qt的，需要用到Object-C？（我啥也不知道

乱讲

**Comment by FTS427** [comment]
行吧(我一个初二的Archlinux党能知道怎么适配MacOS

Quantum
________________________________

**Comment by ghostflyby** [comment]
如果测试环境没问题，那就是打包流程的问题，我已经发现的如下：
1. macOS 目前没有任何 32 位环境受支持，已发布的 32 位和 64 位的包事实上也都是 64 位 intel
2. 缺失 Apple Silicon 支持
3. 可执行文件甚至没有可执行权限
4. 打包后的 App 不符合 App Bundle 的结构

**Comment by LxHTT** [comment]
- 那就可以直接删掉32位mac支持了（
 - Apple Silicon还是得后期多适配，还得考虑兼容性/转译性能（可能）  的问题
 - 既然问题大概率出现在打包，我就得找一些更懂Nuitka打包的人了

**Comment by ghostflyby** [comment]
- 根据我的测试(`file MCSL2`)，目前 Action 打包出来的所有所谓 32 位包实际都是 64 位的
- 根据我的本机（Apple Silicon）打包结果，显然 nuitka 没有正确处理 bundle 目录结构，与 release 里面的包一致。而根据 `nuitka3 —help`，它对 Mac App 的支持是实验性的。
- nuitka 的打包结果架构默认取决于 python 架构
- 额外的，即使是手动运行 macOS 下 dist 目录的二进制，也会报错 segment fault 无法启动

**Comment by LxHTT** [comment]
也就是说Nuitka无法正常打包macOS版本吧（

**Comment by LxHTT** [comment]
> 也就是说Nuitka无法正常打包macOS版本吧（

我现在马上找人问

**Comment by LxHTT** [comment]
把GH Actions有关的代码放在这里：
```shell
  - name: Build Executable on macOS
    if: runner.os == 'macOS'
    run: >
      python -m nuitka
      --standalone
      --enable-plugin=pyqt5
      --onefile
      --output-dir=build
      --assume-yes-for-download
      --disable-console
      --macos-app-mode=gui
      --macos-app-icon=MCSL2.ico
      --company-name="LxHTT"
      --product-name="MCSL 2"
      --file-version=2.0.0
      --macos-app-version=2.0.0
      --file-description="MC Server Launcher 2"
      --macos-create-app-bundle
      MCSL2.py
```

**Comment by LxHTT** [comment]
需要人手测试最新Release的macOS版本能否运行！

**Comment by ghostflyby** [comment]
仍然无法工作。

**Comment by LxHTT** [comment]
由于插件系统的限制，macOS不会提供打包，需要手动下载源代码运行。

**Comment by LxHTT** [comment]
solved with manually packing.
