### ISSUE TITLE
BUG | MessageBox显示异常[无法修复，等待控件作者]

### ISSUE THREAD

**Issue by KLONOA9X6** [MCSLTeam/MCSL2#99]
### MCSL2 系统报告

MCSL2系统报告：
生成时间：2023-08-17 14:08:14
MCSL2版本：2.2.0.1
操作系统：Windows10 10.0.22621
架构：64bit
内存占用：100.56640625MB

### 你在哪方面遇到了问题？

MCSL2终端

### 说明

程序最大化后出现此错误
![image](https://github.com/MCSLTeam/MCSL2/assets/95112579/d670ddc7-c986-4e6d-9a17-612cad36053d)

### 确认

- [X] 我确保我的Issue没有和别人的重复

**Comment by LxHTT** [comment]
该问题疑似为控件库问题。  
将继续跟进控件库作者。

**Comment by StarryCamile** [comment]
矿泉水最新的Commit直接屏蔽该Exception了，暂且能避免最大化循环报错问题

**Comment by LxHTT** [comment]
直接屏蔽这个报错了。  
详见提交https://github.com/MCSLTeam/MCSL2/commit/d3de2bda53bd6573f49e91e8062cfaf8c80cc9b6
